### PR TITLE
Subscription functions

### PR DESCRIPTION
**Pull request by snowdd1**
I would like to introduce two new functions for the convenience of nodeJS programmers to use callbacks for specific addresses.
Instead of subscribing to the 'write' or 'response' events directly and parsing the answers themselves, programmers can use these prepared functions.

registerGA(address, callback)
startMonitor(opts)

With that, eibd can be directly integrate in node apps, such as khaosT/HAP-nodeJS or nfarina/homebridge, and possible several more

Tested on my raspberry with node 0.12.1 and knxd on a separated machine.

### CODE REVIEW

**Comment by andreek** [comment]
Hey,

I think its a great feature to register callbacks for all events on specific addresses. Unfortunately this feature can be introduced to node-eibd more easily than your way. 

```javascript
self.emit(event, tools.addr2str(src, false), tools.addr2str(dest, true), type, value);
```
https://github.com/andreek/node-eibd/blob/master/lib/parser.js#L83

```javascript
self.emit(event, tools.addr2str(src, false), tools.addr2str(dest, true));
```
https://github.com/andreek/node-eibd/blob/master/lib/parser.js#L89

I would extend both lines to emit events for destination address. Like:

```javascript
// emit action event
self.emit(event, tools.addr2str(src, false), tools.addr2str(dest, true), type, value);
// emit dest address event
self.emit(tools.addr2str(dest, true), event, tools.addr2str(src, false), tools.addr2str(dest, true), type, value);
```
https://github.com/andreek/node-eibd/blob/master/lib/parser.js#L83

```javascript
// emit action event
self.emit(event, tools.addr2str(src, false), tools.addr2str(dest, true));
// emit dest address event
self.emit(tools.addr2str(dest, true), event, tools.addr2str(src, false), tools.addr2str(dest, true));
```
https://github.com/andreek/node-eibd/blob/master/lib/parser.js#L89

So you can register your specific callbacks for a address to the parser:
```javascript
parser.on('1/1/1', function(event, src, dest, type, value) {});
```

**Comment by snowdd1** [comment]
Why "unfortunately"? I'm still quite new to JavaScript so I am happy to learn better ways to address those matters!
Do you do the changes and increase the version number?
Regards
Raoul 

Von meinem iPhone gesendet

**Comment by andreek** [comment]
Well, I didn't want to offend you. "Unfortunately" because you take your time and now we implement this feature on a different way. My advice for the future is to create an issue, before you make changes to the code.

I can do it tomorrow.

**Comment by cjk** [comment]
Cool stuff, looking forward to using the new GA-specific callbacks. Thanks @andreek !

**Comment by snowdd1** [comment]
No offense taken! I learned a lot about callbacks when I implemented the first version into my HAP-NodeJS-KNX. Then I thought it might be helpful for others.
But I have one question left: if multiple nodeJS modules want to use one connection instead of instantiating one connection object per module, how can we achieve this? That's why I implemented a central startMonitor() that is making use of nodeJS loading each module only once and by that having a set pseudo-public variables per module. 
Is that only possible by having one central module?

Best regards 
Raoul


Von meinem iPhone gesendet

**Comment by snowdd1** [comment]
Closed as alternative idea will be implemented

**Comment by andreek** [comment]
@snowdd1 Yeah, that is only possible if node-eibd is included once.

**Pull request closed without merging**
