### PR TITLE
Fixed issue #21 on DPT-10 (time) and DPT-11 (date) encoding

### PR DESCRIPTION
**Pull request by marcopiraccini**

### CODE REVIEW

**Comment by marcopiraccini** [comment]
Sure, it's `convertToDPT9` and `convertFromDPT9` better?

**Comment by snowdd1** [comment]
Absolutely.

**Comment by snowdd1** [comment]
But then, we could leave it in the encoder.js and decoder.js and just change L51... :smile: 

May I also suggest to change ALL tests of encoder.js to `encode('TYPE',value)` instead of some references to the direct `encodeDPT9(value)`

**Comment by marcopiraccini** [comment]
OK, done both changes.

**Comment by snowdd1** [comment]
Like! :+1:

**Comment by andreek** [comment]
+1

**Comment by andreek** [comment]
published to npm.

**Pull request merged**
