### PR TITLE
Support for UNIX sockets

### PR DESCRIPTION
**Pull request by snowdd1**
Hi all,
I have been working with knxd using a UNIX socket lately, and have changed 3 lines to enable node_eibd to connect to sockets as well.

I have also modified /bin/groupswrite to support socket syntax, mainly for testing purposes.
Please have a look.

### CODE REVIEW

**Comment by snowdd1** [comment]
Tested on a raspberry2b with rasbian jessie lite, node 4.4.0, and knxd 0.10-13 as of 2016-03-12, featuring a busware pigator single with KNX module.

**Comment by andreek** [comment]
Nice to have socket support. Can you please add the socket option for other bin examples as well?

**Comment by snowdd1** [comment]
Sure, give me a day or two.

**Comment by snowdd1** [comment]
...or three. Found some issues in knxd while testing.

**Comment by snowdd1** [comment]
The conflict is supposed to be the reworked `bin/groupsocketlisten`which I did not merged before re-working. But I incorporated the change, so it's safe to merge.
Hold, I will also increase the patch version number.

**Comment by andreek** [comment]
Okay, I'll have a look later today and I'll publish a new version.

**Comment by andreek** [comment]
Sorry for delayed merging. Can you please verify if everything works as expected over socket connection with the master branch?

**Comment by snowdd1** [comment]
Looks good on my machine. I do a PR for an updated README.md to reflect the changes as well.
Thanks
Raoul

**Pull request merged**
